### PR TITLE
mini build

### PR DESCRIPTION
**Pull request by anglepoised**
Adds a mini build system. I'm using Eleventy primarily because it was easier to lift from another project. I could swap it out for a few separate tools that run a local server and copy assets but figured we might want a stopgap to do file work anyway.

### CODE REVIEW

**Review by monospaced — COMMENTED** [review]
Couple of comments…

* I'm prompted to install `@11ty/eleventy@2.0.1` when running `yarn start`. Should this be included in the deps?
* Should we minimise the output CSS (and HTML) when running `yarn build`? Might squeeze a touch more performance out. `yarn start` maybe fine/better to have un-minimised (avoid having to source-map)?

**Comment by anglepoised** [comment]
> I'm prompted to install `@11ty/eleventy@2.0.1` when running `yarn start`. Should this be included in the deps?

Good catch, had hacked this in the project I lifted it from for some risk reduction.
 
> Should we minimise the output CSS (and HTML) when running `yarn build`? Might squeeze a touch more performance out. `yarn start` maybe fine/better to have un-minimised (avoid having to source-map)?

Done!

**Review by monospaced — COMMENTED** [review]
Another thing I noticed

```
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
```

I did also wonder where `autoprefixer` is picking up its config from. Presummably just the default, which is probably fine. But perhaps we need a `.browserslist`?

**Comment by anglepoised** [comment]
> Another thing I noticed
> 
> ```
> Browserslist: caniuse-lite is outdated. Please run:
>   npx update-browserslist-db@latest
> ```

Aye, fixed this.

> I did also wonder where `autoprefixer` is picking up its config from. Presummably just the default, which is probably fine. But perhaps we need a `.browserslist`?

Yes, this will be the built-in [`defaults`](https://browsersl.ist/#q=defaults) config, which gives us:

```sh
❯ browserslist
and_chr 111
and_ff 110
and_qq 13.1
and_uc 13.4
android 111
chrome 111
chrome 110
chrome 109
chrome 108
edge 111
edge 110
edge 109
firefox 111
firefox 110
firefox 109
firefox 102
ios_saf 16.3
ios_saf 16.2
ios_saf 16.1
ios_saf 16.0
ios_saf 15.6
ios_saf 14.5-14.8
kaios 3.0-3.1
kaios 2.5
op_mini all
op_mob 73
opera 95
opera 94
safari 16.3
safari 16.2
safari 15.6
samsung 20
samsung 19.0
```

Think we'd be fine to use the built-ins during this process, but consider adding a `browserslist` at the tail end of this process when we're looking at browser support and testing etc. In anticipation of your agreement I've added a task to the Pre-merge tidy story but if you think it's going to be easier to build in now, maybe easier to spin out deciding browser support (and adding browserslist) as a separate story and do after this build one is closed?

**Review by monospaced — APPROVED** [review]

**Pull request merged**
